server:
  port: 9090

spring:
  cloud:
    config:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AuthDBForProject
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop

authserviceconfig:
  secrets:
    secret-key: ${HR_SYSTEM_KEY}
    issuer:  ${HR_SYSTEM_ISSUER}

rabbitmq:
  mail-queue-guest: mailQueue
  mail-bindingKey: mailBindingKey

  auth-exchange: authExchange

  register-guest-queue: registerGuestQueue
  register-guest-bindingKey: registerGuestBindingKey

  register-guest-activation-queue: registerGuestActivationQueue
  register-guest-activation-bindingKey: registerGuestActivationBindingKey

  register-supervisor-queue: registerSupervisorQueue
  register-supervisor-bindingKey: registerSupervisorBindingKey

  registration-decision-auth-queue: registrationDecisionAuthQueue # Volkan: Admindeki accept/decline'ı dinleyecek kuyruk adını ekledim buraya.
#
#  active-status-queue: activeStatusQueue
#  active-status-bindingKey: activeStatusBindingKey

