#server:
#  port: 80 # 80 / 8080 default portlarımızdı.
#
#spring:
#  main:
#    web-application-type: reactive
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#    service:
#      name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: auth-service  # benim koyduğum unique bir isim
#          uri: http://localhost:9090  # bu urlden gelen
#          predicates:
#            - Path=/api/v1/auth/**   # auth ile başlayan isteklerin sonu ne olursa olsun yakalamak istiyorum
#          filters: # Circuit Breakers ile ekledik : https://docs.spring.io/spring-cloud-gateway/docs/3.1.8/reference/html/#fallback-headers
#            - name: CircuitBreaker
#              args:
#                name: authCircuitBreaker
#                fallbackUri: forward:/fallback/auth
#        - id: user-profile-service
#          uri: http://localhost:9091
#          predicates:
#            - Path=/api/v1/user/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: userProfileCircuitBreaker
#                fallbackUri: forward:/fallback/user
#      default-filters: # burayı dökümantasyondan öğrendik
#        # http://localhost/auth/findbyid/1
#        # (?<segment>.*)   -->  auth/findbyid/1
#        #   /$\{segment}   -->  http://localhost:9090/auth/findbyid/1
#        - RewritePath=/(?<segment>.*), /$\{segment} # RewritePath=/(?<segment>.*),/api/v1/$\{segment}   eğer çoğu urlde kullandığınız statik değerler var ise, api/v1 gibi...