server:
  port: 9094
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: HRSystem
      username: devAvs
      password: musketeers!123
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
guest-service-config:
  jwt:
    issuer: ${HR_SYSTEM_ISSUER}
    secret-key: ${HR_SYSTEM_KEY}
  rabbitmq:
    register-guest-queue: registerGuestQueue
    register-guest-activation-queue: registerGuestActivationQueue
    expiration-timeout: 5000