server:
  port: 9096
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  mail:
    host: smtp.gmail.com
    port: 587
    username: infomusketeershmrs@gmail.com
    password: ${HMRS_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail-service-config:
  rabbitmq:
    activation-guest-queue: mailQueue
    mail-queue-personnel: mailQueuePersonnel
    send-day-off-status-change-notification-to-mail-service-queue: sendDayOffStatusChangeNotificationToMailServiceQueue
    send-advance-status-change-notification-to-mail-service-queue: sendAdvanceStatusChangeNotificationToMailServiceQueue
    send-spending-status-change-notification-to-mail-service-queue: sendSpendingStatusChangeNotificationToMailServiceQueue
  mail:
    gateway-url: http://localhost:80