server:
  port: 9092
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: HRSystem
      username: devAvs
      password: musketeers!123
  cloud:
    config:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
supervisor-service-config:
  jwt:
    issuer: ${HR_SYSTEM_ISSUER}
    secret-key: ${HR_SYSTEM_KEY}
  rabbitmq:
    register-supervisor-queue: registerSupervisorQueue
    get-supervisor-queue: getSupervisorQueue
    registration-decision-supervisor-queue: registrationDecisionSupervisorQueue
    supervisor-activation-exchange: supervisorActivationExchange
    supervisor-activation-company-queue: supervisorActivationCompanyQueue
    supervisor-activation-company-binding-key: supervisorActivationCompanyBindingKey
    get-company-id-from-supervisor-queue: getCompanyIdFromSupervisorQueue
    get-company-id-supervisor-queue: getCompanyIdSupervisorQueue
    get-company-supervisors-supervisor-queue: getCompanySupervisorsSupervisorQueue







#spring:
#  cloud:
#    config:
#      uri: ${config-server-url} #http://localhost:8888
#  config:
#    import: "configserver:"
#  application:
#    name: supervisor-service-application