server:
  port: 9095
spring:
  cloud:
    config:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CompanyDb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
company-service-config:
  jwt:
    issuer: ${HR_SYSTEM_ISSUER}
    secret-key: ${HR_SYSTEM_KEY}

rabbitmq:
  exchange-name: companyExchange
  supervisor-activation-company-queue: supervisorActivationCompanyQueue
  get-company-id-from-supervisor-queue: getCompanyIdFromSupervisorQueue
  get-company-id-from-supervisor-binding-key: getCompanyIdFromSupervisorBindingKey
  create-personnel-company-queue: createPersonnelCompanyQueue

