server:
  port: 9093
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrsystem
    username: devAvs
    password: musketeers!123
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    config:
      enabled: false










#spring:
#  cloud:
#    config:
#      uri: ${CONFIG_URI}
#  config:
#    import: "configserver:"
#  application:
#    name: admin-service-application