server:
  port: 9094
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: HRSystem
      username: devAvs
      password: musketeers!123
  cloud:
    config:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
guest-service-config:
  jwt:
    issuer: ${MUSKETEERS_GUEST_SERVICE_ISSUER}
    secret-key: ${MUSKETEERS_GUEST_SERVICE_SECRET_KEY}
  rabbitmq:
    auth-exchange: authExchange
    register-guest-queue: registerQueue
    register-guest-bindingKey: registerBindingKey
    activation-guest-queue: activationQueue
    activation-guest-bindingKey: activationBindingKey




#spring:
#  cloud:
#    config:
#      uri: ${config-server-url} #http://localhost:8888
#  config:
#    import: "configserver:"
#  application:
#    name: person-service-application