server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${HMRS_GIT_URI}
          default-label: main
          skip-ssl-validation: true
          refresh-rate: 10
          username: alivolkansahin
          password: ${HMRS_GIT_KEY}