server:
  port: 9087
spring:
  cloud:
    config:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SpendingDBForProject
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
spending-service-config:
  jwt:
    issuer: ${HR_SYSTEM_ISSUER}
    secret-key: ${HR_SYSTEM_KEY}
  rabbitmq:
    spending-exchange: spendingExchange
    expiration-timeout: 5000

