server:
  port: 9087
spring:
  cloud:
    config:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SpendingDBForProject
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
spending-service-config:
  jwt:
    issuer: ${HR_SYSTEM_ISSUER}
    secret-key: ${HR_SYSTEM_KEY}

rabbitmq:
  exchange-name: spendingExchange
#  supervisor-activation-company-queue: supervisorActivationCompanyQueue
#  get-company-id-from-supervisor-queue: getCompanyIdFromSupervisorQueue
#  get-company-id-from-supervisor-binding-key: getCompanyIdFromSupervisorBindingKey
#  create-personnel-company-queue: createPersonnelCompanyQueue
#  get-company-details-by-comment-company-queue: getCompanyDetailsByCommentCompanyQueue
#  get-company-supervisors-supervisor-queue: getCompanySupervisorsSupervisorQueue
#  get-company-supervisors-supervisor-binding-key: getCompanySupervisorsSupervisorBindingKey
#  get-company-details-by-personnel-queue: getCompanyDetailsByPersonnelQueue
#  company-status-check-queue: companyStatusCheckQueue
#  search-for-company-name-queue: searchForCompanyNameQueue
  expiration-timeout: 5000

