#server:
#  port: 8888
#
#spring:
#  profiles:
#    active: native
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#    service:
#      name: config-service
#
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config-repo