server:
  port: 9091
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: HRSystem
      username: devAvs
      password: musketeers!123
  cloud:
    config:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
personnel-service-config:
  jwt:
    issuer: ${MUSKETEERS_GUEST_SERVICE_ISSUER} #buraya genel ad lazım bütün servisler için, aynı olmalı çünkü decode işlemi için.
    secret-key: ${MUSKETEERS_GUEST_SERVICE_SECRET_KEY}
  rabbitmq:
    auth-exchange: authExchange
    personnel-register-queue: personnelRegisterQueue
    personnel-register-bindingKey: personnelRegisterBindingKey
    personnel-activation-queue: personnelActivationQueue
    personnel-activation-bindingKey: personnelActivationBindingKey






#spring:
#  cloud:
#    config:
#      uri: ${config-server-url} #http://localhost:8888
#  config:
#    import: "configserver:"
#  application:
#    name: person-service-application