server:
  port: 9091
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: HRSystem
      username: devAvs
      password: musketeers!123
  cloud:
    config:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
personnel-service-config:
  jwt:
    issuer: ${HR_SYSTEM_ISSUER}
    secret-key: ${HR_SYSTEM_KEY}
  rabbitmq:
    create-personnel-exchange: createPersonnelExchange
    create-personnel-auth-queue: createPersonnelAuthQueue
    create-personnel-auth-binding-key: createPersonnelAuthBindingKey
    create-personnel-company-queue: createPersonnelCompanyQueue
    create-personnel-company-binding-key: createPersonnelCompanyBindingKey
    get-company-id-supervisor-queue: getCompanyIdSupervisorQueue
    get-company-id-supervisor-binding-key: getCompanyIdSupervisorBindingKey
    add-comment-personnel-queue: addCommentPersonnelQueue
    get-personnel-details-by-comment-personnel-queue: getPersonnelDetailsByCommentPersonnelQueue
    create-personnel-from-supervisor-queue: createPersonnelFromSupervisorQueue
    get-company-details-by-personnel-queue: getCompanyDetailsByPersonnelQueue
    get-company-details-by-personnel-binding-key: getCompanyDetailsByPersonnelBindingKey
    update-personnel-by-id-auth-queue: updatePersonnelByIdAuthQueue
    update-personnel-by-id-auth-binding-key: updatePersonnelByIdAuthBindingKey
    update-personnel-by-id-supervisor-queue: updatePersonnelByIdSupervisorQueue
    update-personnel-by-id-supervisor-binding-key: updatePersonnelByIdSupervisorBindingKey
    get-company-id-for-user-login-queue: getCompanyIdForUserLoginQueue
    expiration-timeout: 5000




#spring:
#  cloud:
#    config:
#      uri: ${config-server-url} #http://localhost:8888
#  config:
#    import: "configserver:"
#  application:
#    name: person-service-application